chore: Update TLS secret and Ghost configuration (#261)

diff --git a/deploy/05-mysql.yaml b/deploy/05-mysql.yaml
--- a/deploy/05-mysql.yaml
+++ b/deploy/05-mysql.yaml
@@ -1,59 +1,59 @@
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
-  name: mysql-ghost-on-kubernetes
+  name: ghost-on-kubernetes-mysql
   namespace: ghost-on-kubernetes
   labels:
-    app: mysql-ghost-on-kubernetes
-    app.kubernetes.io/name: mysql-ghost-on-kubernetes
+    app: ghost-on-kubernetes-mysql
+    app.kubernetes.io/name: ghost-on-kubernetes-mysql
     app.kubernetes.io/instance: ghost-on-kubernetes
-    app.kubernetes.io/version: "5.87"
+    app.kubernetes.io/version: '5.92'
     app.kubernetes.io/component: database
     app.kubernetes.io/part-of: ghost-on-kubernetes
-    app.kubernetes.io/managed-by: sredevopsorg
+    
 spec:
-  serviceName: service-mysql-ghost-on-kubernetes
+  serviceName: ghost-on-kubernetes-mysql-service
   replicas: 1
   selector:
     matchLabels:
-      app: mysql-ghost-on-kubernetes
+      app: ghost-on-kubernetes-mysql
   template:
     metadata:
       labels:
-        app: mysql-ghost-on-kubernetes
+        app: ghost-on-kubernetes-mysql
     spec:
       initContainers:
-      - name: mysql-ghost-on-kubernetes-init
+      - name: ghost-on-kubernetes-mysql-init
         securityContext:
           allowPrivilegeEscalation: false
           privileged: false
           readOnlyRootFilesystem: true
         image: docker.io/busybox:stable-musl
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always # You can change this value according to your needs
         command:
         - /bin/sh
         - -c
         - |
           set -e
-          echo 'Changing ownership of mysql mount directory to 999:999'
-          chown -Rfv 999:999 /mnt/mysql || echo 'Error changing ownership of mysql mount directory to 999:999'
-          echo 'Changing ownership of tmp mount directory to 999:999'
-          chown -Rfv 999:999 /mnt/tmp || echo 'Error changing ownership of tmp mount directory to 999:999'
-          echo 'Changing ownership of socket mount directory to 999:999'
-          chown -Rfv 999:999 /mnt/var/run/mysqld || echo 'Error changing ownership of socket mount directory to 999:999'
+          echo 'Changing ownership of mysql mount directory to 65534:65534'
+          chown -Rfv 65534:65534 /mnt/mysql || echo 'Error changing ownership of mysql mount directory to 65534:65534'
+          echo 'Changing ownership of tmp mount directory to 65534:65534'
+          chown -Rfv 65534:65534 /mnt/tmp || echo 'Error changing ownership of tmp mount directory to 65534:65534'
+          echo 'Changing ownership of socket mount directory to 65534:65534'
+          chown -Rfv 65534:65534 /mnt/var/run/mysqld || echo 'Error changing ownership of socket mount directory to 65534:65534'
           
           
         volumeMounts:
-        - name: mysql-ghost-on-kubernetes-volume
+        - name: ghost-on-kubernetes-mysql-volume
           mountPath: /mnt/mysql
           subPath: mysql-empty-subdir
           readOnly: false
 
-        - name: mysql-ghost-on-kubernetes-tmp
+        - name: ghost-on-kubernetes-mysql-tmp
           mountPath: /mnt/tmp
           readOnly: false
 
-        - name: mysql-ghost-on-kubernetes-socket
+        - name: ghost-on-kubernetes-mysql-socket
           mountPath: /mnt/var/run/mysqld
           readOnly: false
         
@@ -67,23 +67,23 @@ spec:
             cpu: 900m
 
       containers:
-      - name: mysql-ghost-on-kubernetes
+      - name: ghost-on-kubernetes-mysql
         securityContext:
           allowPrivilegeEscalation: false
           privileged: false
           readOnlyRootFilesystem: true
           runAsNonRoot: true
-          runAsUser: 999
+          runAsUser: 65534
 
         image: docker.io/mysql:8.4
-        imagePullPolicy: IfNotPresent # You can change this value according to your needs
+        imagePullPolicy: Always # You can change this value according to your needs
         envFrom:
         - secretRef:
-            name: mysql-ghost-on-kubernetes-config
+            name: ghost-on-kubernetes-mysql-env
         resources:
           requests:
             memory: 500Mi # You can change this value according to your needs
-            cpu: 100m # You can change this value according to your needs
+            cpu: 300m # You can change this value according to your needs
           limits:
             memory: 1Gi # You can change this value according to your needs
             cpu: 900m # You can change this value according to your needs
@@ -92,43 +92,43 @@ spec:
           protocol: TCP
           name: mysqlgh
         volumeMounts:
-        - name: mysql-ghost-on-kubernetes-volume
+        - name: ghost-on-kubernetes-mysql-volume
           mountPath: /var/lib/mysql
           subPath: mysql-empty-subdir
           readOnly: false
 
-        - name: mysql-ghost-on-kubernetes-tmp
+        - name: ghost-on-kubernetes-mysql-tmp
           mountPath: /tmp
           readOnly: false
 
-        - name: mysql-ghost-on-kubernetes-socket
+        - name: ghost-on-kubernetes-mysql-socket
           mountPath: /var/run/mysqld
           readOnly: false
 
       automountServiceAccountToken: false
 
       # Optional: Uncomment the following to specify node selectors
-      # affinity:
-      #   nodeAffinity:
-      #     requiredDuringSchedulingIgnoredDuringExecution:
-      #       nodeSelectorTerms:
-      #         - matchExpressions:
-      #             - key: node-role.kubernetes.io/worker
-      #               operator: In
-      #               values:
-      #                 - "true"
+      affinity:
+        nodeAffinity:
+          requiredDuringSchedulingIgnoredDuringExecution:
+            nodeSelectorTerms:
+              - matchExpressions:
+                  - key: node-role.kubernetes.io/worker
+                    operator: In
+                    values:
+                      - 'true'
 
       securityContext:
         seccompProfile:
           type: RuntimeDefault
 
       volumes:
-      - name: mysql-ghost-on-kubernetes-volume
+      - name: ghost-on-kubernetes-mysql-volume
         persistentVolumeClaim:
-          claimName: mysql-ghost-on-kubernetes-pvc
-      - name: mysql-ghost-on-kubernetes-tmp
+          claimName: ghost-on-kubernetes-mysql-pvc
+      - name: ghost-on-kubernetes-mysql-tmp
         emptyDir:
           sizeLimit: 128Mi
-      - name: mysql-ghost-on-kubernetes-socket
+      - name: ghost-on-kubernetes-mysql-socket
         emptyDir:
           sizeLimit: 128Mi
