chore: Update PVC storage size to 1Gi, add MYSQL_HOST to secrets, and update Ghost configuration files

diff --git a/deploy/05-mysql.yaml b/deploy/05-mysql.yaml
--- a/deploy/05-mysql.yaml
+++ b/deploy/05-mysql.yaml
@@ -38,12 +38,11 @@ spec:
         - |
           set -e
           echo 'Changing ownership of mysql mount directory to 999:999'
-          chown -Rfv 999:999 /mnt/mysql || echo 'Error changing ownership of mysql mount directory to 999:999' && true
+          chown -Rfv 999:999 /mnt/mysql || echo 'Error changing ownership of mysql mount directory to 999:999'
           echo 'Changing ownership of tmp mount directory to 999:999'
-          chown -Rfv 999:999 /mnt/tmp || echo 'Error changing ownership of tmp mount directory to 999:999' && true
+          chown -Rfv 999:999 /mnt/tmp || echo 'Error changing ownership of tmp mount directory to 999:999'
           echo 'Changing ownership of socket mount directory to 999:999'
-          chown -Rfv 999:999 /mnt/var/run/mysqld || echo 'Error changing ownership of socket mount directory to 999:999' && true
-          exit 0
+          chown -Rfv 999:999 /mnt/var/run/mysqld || echo 'Error changing ownership of socket mount directory to 999:999'
           
           
         volumeMounts:
@@ -78,7 +77,7 @@ spec:
           runAsNonRoot: true
           runAsUser: 999
 
-        image: docker.io/mysql:8.2
+        image: docker.io/mysql:8.4
         imagePullPolicy: IfNotPresent # You can change this value according to your needs
         envFrom:
         - secretRef:
@@ -86,7 +85,7 @@ spec:
         resources:
           requests:
             memory: 500Mi # You can change this value according to your needs
-            cpu: 400m # You can change this value according to your needs
+            cpu: 100m # You can change this value according to your needs
           limits:
             memory: 1Gi # You can change this value according to your needs
             cpu: 900m # You can change this value according to your needs
