Update storageClassName and service labels***
***Update Dockerfile and deployment resources

diff --git a/deploy/05-mysql.yaml b/deploy/05-mysql.yaml
--- a/deploy/05-mysql.yaml
+++ b/deploy/05-mysql.yaml
@@ -21,9 +21,6 @@ spec:
       labels:
         app: mysql-ghost-k8s
         app.kubernetes.io/name: mysql-ghost-k8s
-        app.kubernetes.io/instance: ghost-k8s
-        app.kubernetes.io/version: "5.8"
-        app.kubernetes.io/component: database
       annotations:
         container.apparmor.security.beta.kubernetes.io/mysql-ghost-k8s: runtime/default
     spec:
@@ -41,19 +38,35 @@ spec:
         - -c
         - |
           set -ex
-          chown -R 999:999 /mnt/mysql || true
+          echo 'Changing ownership of mysql mount directory to 999:999'
+          chown -R 999:999 /mnt/mysql || echo 'Error changing ownership of mysql mount directory to 999:999' && true
+          echo 'Changing ownership of tmp mount directory to 999:999'
+          chown -R 999:999 /mnt/tmp || echo 'Error changing ownership of tmp mount directory to 999:999' && true
+          echo 'Changing ownership of socket mount directory to 999:999'
+          chown -R 999:999 /mnt/var/run/mysqld || echo 'Error changing ownership of socket mount directory to 999:999' && true
+          exit 0
+          
+          
         volumeMounts:
         - name: mysql-ghost-k8s-volume
           mountPath: /mnt/mysql
           subPath: mysql-empty-dir
+
+        - name: mysql-ghost-k8s-tmp
+          mountPath: /mnt/tmp
+          readOnly: false
+
+        - name: mysql-ghost-k8s-socket
+          mountPath: /mnt/var/run/mysqld
+          readOnly: false
+
         resources:
           requests:
-            memory: 100Mi
-            cpu: 100m
+            memory: 400Mi
+            cpu: 300m
           limits:
-            memory: 200Mi
-            cpu: 200m
-
+            memory: 1000Mi # You c
+            cpu: 1000m
 
       containers:
       - name: mysql-ghost-k8s
@@ -65,17 +78,17 @@ spec:
           runAsUser: 999
 
         image: docker.io/mysql:8.2
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: IfNotPresent # You can change this value according to your needs
         envFrom:
         - secretRef:
             name: mysql-ghost-k8s
         resources:
           requests:
-            memory: 200Mi
-            cpu: 100m
+            memory: 400Mi
+            cpu: 300m
           limits:
-            memory: 1Gi
-            cpu: 1000m
+            memory: 1Gi # You can change this value according to your needs
+            cpu: 1000m # You can change this value according to your needs
         ports:
         - containerPort: 3306
           protocol: TCP
@@ -84,13 +97,16 @@ spec:
         - name: mysql-ghost-k8s-volume
           mountPath: /var/lib/mysql
           subPath: mysql-empty-dir
+
         - name: mysql-ghost-k8s-tmp
           mountPath: /tmp
           readOnly: false
+
         - name: mysql-ghost-k8s-socket
           mountPath: /var/run/mysqld
           readOnly: false
       automountServiceAccountToken: false
+
       # Optional: Uncomment the following to specify node selectors
       # affinity:
       #   nodeAffinity:
@@ -105,6 +121,7 @@ spec:
       securityContext:
         seccompProfile:
           type: RuntimeDefault
+
       volumes:
       - name: mysql-ghost-k8s-volume
         persistentVolumeClaim:
