chore: Update TLS secret and Ghost configuration
This commit adds a new TLS secret in the `ghost-on-kubernetes` namespace, with the name `tls-secret`. It also updates the Ghost configuration in the `01-ghost-config.yaml` file, changing the URLs to `https://yourdomain.tld`. These changes are necessary to ensure proper SSL/TLS encryption and to reflect the correct domain name.

diff --git a/deploy/05-mysql.yaml b/deploy/05-mysql.yaml
--- a/deploy/05-mysql.yaml
+++ b/deploy/05-mysql.yaml
@@ -7,10 +7,10 @@ metadata:
     app: mysql-ghost-on-kubernetes
     app.kubernetes.io/name: mysql-ghost-on-kubernetes
     app.kubernetes.io/instance: ghost-on-kubernetes
-    app.kubernetes.io/version: "5.87"
+    app.kubernetes.io/version: '5.89'
     app.kubernetes.io/component: database
     app.kubernetes.io/part-of: ghost-on-kubernetes
-    app.kubernetes.io/managed-by: sredevopsorg
+    
 spec:
   serviceName: service-mysql-ghost-on-kubernetes
   replicas: 1
@@ -29,18 +29,18 @@ spec:
           privileged: false
           readOnlyRootFilesystem: true
         image: docker.io/busybox:stable-musl
-        imagePullPolicy: IfNotPresent
+        imagePullPolicy: Always # You can change this value according to your needs
         command:
         - /bin/sh
         - -c
         - |
           set -e
-          echo 'Changing ownership of mysql mount directory to 999:999'
-          chown -Rfv 999:999 /mnt/mysql || echo 'Error changing ownership of mysql mount directory to 999:999'
-          echo 'Changing ownership of tmp mount directory to 999:999'
-          chown -Rfv 999:999 /mnt/tmp || echo 'Error changing ownership of tmp mount directory to 999:999'
-          echo 'Changing ownership of socket mount directory to 999:999'
-          chown -Rfv 999:999 /mnt/var/run/mysqld || echo 'Error changing ownership of socket mount directory to 999:999'
+          echo 'Changing ownership of mysql mount directory to 65534:65534'
+          chown -Rfv 65534:65534 /mnt/mysql || echo 'Error changing ownership of mysql mount directory to 65534:65534'
+          echo 'Changing ownership of tmp mount directory to 65534:65534'
+          chown -Rfv 65534:65534 /mnt/tmp || echo 'Error changing ownership of tmp mount directory to 65534:65534'
+          echo 'Changing ownership of socket mount directory to 65534:65534'
+          chown -Rfv 65534:65534 /mnt/var/run/mysqld || echo 'Error changing ownership of socket mount directory to 65534:65534'
           
           
         volumeMounts:
@@ -73,17 +73,17 @@ spec:
           privileged: false
           readOnlyRootFilesystem: true
           runAsNonRoot: true
-          runAsUser: 999
+          runAsUser: 65534
 
         image: docker.io/mysql:8.4
-        imagePullPolicy: IfNotPresent # You can change this value according to your needs
+        imagePullPolicy: Always # You can change this value according to your needs
         envFrom:
         - secretRef:
             name: mysql-ghost-on-kubernetes-config
         resources:
           requests:
             memory: 500Mi # You can change this value according to your needs
-            cpu: 100m # You can change this value according to your needs
+            cpu: 300m # You can change this value according to your needs
           limits:
             memory: 1Gi # You can change this value according to your needs
             cpu: 900m # You can change this value according to your needs
@@ -108,15 +108,15 @@ spec:
       automountServiceAccountToken: false
 
       # Optional: Uncomment the following to specify node selectors
-      # affinity:
-      #   nodeAffinity:
-      #     requiredDuringSchedulingIgnoredDuringExecution:
-      #       nodeSelectorTerms:
-      #         - matchExpressions:
-      #             - key: node-role.kubernetes.io/worker
-      #               operator: In
-      #               values:
-      #                 - "true"
+      affinity:
+        nodeAffinity:
+          requiredDuringSchedulingIgnoredDuringExecution:
+            nodeSelectorTerms:
+              - matchExpressions:
+                  - key: node-role.kubernetes.io/worker
+                    operator: In
+                    values:
+                      - 'true'
 
       securityContext:
         seccompProfile:
diff --git a/deploy/06-ghost-deployment.yaml b/deploy/06-ghost-deployment.yaml
--- a/deploy/06-ghost-deployment.yaml
+++ b/deploy/06-ghost-deployment.yaml
@@ -7,12 +7,13 @@ metadata:
     app: ghost-on-kubernetes
     app.kubernetes.io/name: ghost-on-kubernetes
     app.kubernetes.io/instance: ghost-on-kubernetes
-    app.kubernetes.io/version: "5.87"
+    app.kubernetes.io/version: '5.89'
     app.kubernetes.io/component: ghost
     app.kubernetes.io/part-of: ghost-on-kubernetes
-    app.kubernetes.io/managed-by: sredevopsorg
+    
     
 spec:
+  # If you want HA for your Ghost instance, you can increase the number of replicas AFTER creation and you need to adjust the storage class. See 02-pvc.yaml for more information.
   replicas: 1
   selector:
     matchLabels:
@@ -39,10 +40,10 @@ spec:
           sizeLimit: 64Mi
 
       initContainers:
-      - name: ghost-on-kubernetes-init
+      - name: permissions-fix
+        imagePullPolicy: Always
         image: docker.io/busybox:stable-musl
         env:
-
         - name: GHOST_INSTALL
           value: /home/nonroot/app/ghost
         - name: GHOST_CONTENT
@@ -65,7 +66,7 @@ spec:
           - |
             set -e
 
-            export DIRS="files logs apps themes data public settings images media"
+            export DIRS='files logs apps themes data public settings images media'
             echo 'Check if base dirs exists, if not, create them'
             echo "Directories to check: $DIRS"
             for dir in $DIRS; do
@@ -76,10 +77,11 @@ spec:
             done
 
             echo "Changing ownership of $GHOST_CONTENT/themes directory"
-            chown -Rfv 65532:65532 $GHOST_CONTENT/themes || echo "Error changing ownership of $GHOST_CONTENT themes directory"
+            chown -Rf 65532:65532 $GHOST_CONTENT/themes || echo "Error changing ownership of $GHOST_CONTENT/themes directory"
 
             echo "Changing ownership of $GHOST_CONTENT/public directory"
-            chown -Rfv 65532:65532 $GHOST_CONTENT/public || echo "Error changing ownership of $GHOST_CONTENT public directory"
+            chown -Rf 65532:65532 $GHOST_CONTENT/public || echo "Error changing ownership of $GHOST_CONTENT public directory"
+            exit 0
 
 
         volumeMounts:
@@ -97,48 +99,46 @@ spec:
           protocol: TCP
 
         # You should uncomment the following lines in production. Change the values according to your environment.
-        # readinessProbe:
-        #   httpGet:
-        #     path: /ghost/api/v4/admin/site/
-        #     port: ghk8s
-        #     httpHeaders:
-        #     - name: X-Forwarded-Proto
-        #       value: https
-        #     - name: Host
-        #       value: tests.yourdomain.com
-        #   periodSeconds: 3600
-        #   timeoutSeconds: 5
-        #   successThreshold: 1
-        #   failureThreshold: 1
-        #   initialDelaySeconds: 60
+        readinessProbe:
+          httpGet:
+            path: /ghost/api/v4/admin/site/
+            port: ghk8s
+            httpHeaders:
+            - name: X-Forwarded-Proto
+              value: https
+            - name: Host
+              value: yourdomain.tld
+          periodSeconds: 10
+          timeoutSeconds: 3
+          successThreshold: 1
+          failureThreshold: 3
+          initialDelaySeconds: 15
 
-        # livenessProbe:
-        #   httpGet:
-        #     path: /ghost/api/v4/admin/site/
-        #     port: ghk8s
-        #     httpHeaders:
-        #     - name: X-Forwarded-Proto
-        #       value: https
-        #     - name: Host
-        #       value: tests.yourdomain.com
-        #   periodSeconds: 3600
-        #   timeoutSeconds: 3
-        #   successThreshold: 1
-        #   failureThreshold: 1
-        #   initialDelaySeconds: 60
+        livenessProbe:
+          httpGet:
+            path: /ghost/api/v4/admin/site/
+            port: ghk8s
+            httpHeaders:
+            - name: X-Forwarded-Proto
+              value: https
+            - name: Host
+              value: yourdomain.tld
+          periodSeconds: 300
+          timeoutSeconds: 3
+          successThreshold: 1
+          failureThreshold: 2
+          initialDelaySeconds: 30
 
         env:
         - name: NODE_ENV
           value: production
-        - name: TZ
-          value: America/Santiago
         resources:
           limits:
             cpu: 800m
             memory: 800Mi
           requests:
             cpu: 100m
-            memory: 200Mi
+            memory: 256Mi
 
         volumeMounts:
         - name: k8s-ghost-content
@@ -159,23 +159,20 @@ spec:
 
 
       restartPolicy: Always
-      terminationGracePeriodSeconds: 30
+      terminationGracePeriodSeconds: 15
       dnsPolicy: ClusterFirst
       # Optional: Uncomment the following to specify node selectors
-      # affinity:
-      #   nodeAffinity:
-      #     requiredDuringSchedulingIgnoredDuringExecution:
-      #       nodeSelectorTerms:
-      #         - matchExpressions:
-      #             - key: node-role.kubernetes.io/worker
-      #               operator: In
-      #               values:
-      #                 - "true"
-
-
+      affinity:
+        nodeAffinity:
+          requiredDuringSchedulingIgnoredDuringExecution:
+            nodeSelectorTerms:
+              - matchExpressions:
+                  - key: node-role.kubernetes.io/worker
+                    operator: In
+                    values:
+                      - 'true'
       securityContext: {}
-      schedulerName: default-scheduler
-  minReadySeconds: 15
+  minReadySeconds: 5
   strategy:
     type: RollingUpdate
     rollingUpdate:
