chore: Update contributing guidelines and deployment script

diff --git a/deploy/06-ghost-deployment.yaml b/deploy/06-ghost-deployment.yaml
--- a/deploy/06-ghost-deployment.yaml
+++ b/deploy/06-ghost-deployment.yaml
@@ -69,13 +69,9 @@ spec:
             for dir in $DIRS; do
               if [ ! -d $GHOST_CONTENT/$dir ]; then
                 echo "Creating $GHOST_CONTENT/$dir directory"
-                mkdir -pv $GHOST_CONTENT/$dir && chown -Rf 1000:1000 $GHOST_CONTENT/$dir || echo "Error creating $GHOST_CONTENT/$dir directory" && true
+                mkdir -pv $GHOST_CONTENT/$dir && chown -Rfv 1000:1000 $GHOST_CONTENT/$dir || echo "Error creating $GHOST_CONTENT/$dir directory" && true
               fi
             done
-
-
-            echo 'Delete and clean $GHOST_CONTENT/public directory and recreate it'
-            rm -rfv $GHOST_CONTENT/public && mkdir -pv $GHOST_CONTENT/public || echo 'Error deleting and cleaning $GHOST_CONTENT/public directory and recreating it' && true
 
             echo 'Check if the directory $GHOST_CONTENT/themes ownership is different from UID 1000 and GID 1000, if so, change it to 1000:1000 recursively and verbose.'
             if [ "$(stat -c '%u:%g' $GHOST_CONTENT/themes)" != "1000:1000" ]; then
@@ -86,7 +82,7 @@ spec:
             echo 'Check if the directory $GHOST_CONTENT/public ownership is different from UID 1000 and GID 1000, if so, change it to 1000:1000 recursively and verbose.'
             if [ "$(stat -c '%u:%g' $GHOST_CONTENT/public)" != "1000:1000" ]; then
               echo 'Changing ownership of $GHOST_CONTENT/public directory to 1000:1000'
-              chown -Rf 1000:1000 $GHOST_CONTENT/public || echo 'Error changing ownership of $GHOST_CONTENT/public directory to 1000:1000' && true
+              chown -Rfv 1000:1000 $GHOST_CONTENT/public || echo 'Error changing ownership of $GHOST_CONTENT/public directory to 1000:1000' && true
             fi
 
         volumeMounts:
@@ -151,7 +147,7 @@ spec:
           runAsUser: 1000
 
       restartPolicy: Always
-      terminationGracePeriodSeconds: 15
+      terminationGracePeriodSeconds: 30
       dnsPolicy: ClusterFirst
       # Optional: Uncomment the following to specify node selectors
       # affinity:
