Add fetch-depth option to checkout step in build-custom-image.yaml

diff --git a/.github/workflows/build-custom-image.yaml b/.github/workflows/build-custom-image.yaml
--- a/.github/workflows/build-custom-image.yaml
+++ b/.github/workflows/build-custom-image.yaml
@@ -34,6 +34,8 @@ jobs:
       -
         name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Install Cosign
         uses: sigstore/cosign-installer@v3.2.0
@@ -74,16 +76,32 @@ jobs:
         id: meta
         uses: docker/metadata-action@v5
         with:
-          images: ghcr.io/${{ github.repository }}
-            # ghcr.io/${{ github.repository }}
-            # quay.io/${{ vars.QUAY_USER }}/${{ github.event.repository.name }}
-            # docker.io/${{ vars.DOCKER_USER }}/${{ github.event.repository.name }}
-          context: git
+          # images: |
+          #   name/foo
+          #   ghcr.io/name/bar
+          #   # or
+          #   name=name/foo
+          #   name=ghcr.io/name/bar
+          images: |
+            name=ghcr.io/${{ github.repository }}
+#           ghcr.io/${{ github.repository }}
+#           quay.io/${{ vars.QUAY_USER }}/${{ github.event.repository.name }}
+#           docker.io/${{ vars.DOCKER_USER }}/${{ github.event.repository.name }}
+          flavor: |
+            latest=auto
+            prefix=
+            suffix=
           tags: |
-            type=sha,format=long
             type=ref,event=branch
             type=ref,event=tag
-#            type=raw,value=latest
+            type=sha,format=long
+#            type=schedule
+#            type=semver,pattern={{version}}
+#            type=semver,pattern={{major}}.{{minor}}
+#            type=semver,pattern={{major}}
+#            type=ref,event=branch
+#            type=ref,event=pr
+#            type=sha
 #            type=ref,event=push
 #            type=raw,value=${{ steps.versions.outputs.MANUAL_TAG }}
 #            type=raw,value=v${{ steps.versions.outputs.GHOST_VERSION }}
@@ -133,8 +151,6 @@ jobs:
             GHOST_VERSION=${{ steps.versions.outputs.GHOST_VERSION }} 
 
 
-
-
       - name: Sign the images with GitHub
         id: sign
         continue-on-error: true
@@ -156,12 +172,17 @@ jobs:
           DIGEST: ${{ steps.build-and-push.outputs.digest }}
           TAGS: ${{ steps.meta.outputs.tags }}
         run: |
-          # Look for the main and latest tag and sign them with the GitHub OIDC Token
-          for tag in ${{ steps.meta.outputs.tags }}; do
-            if [[ $tag == *main* ]] || [[ $tag == *latest* ]]; then
-              cosign sign --yes --verbose "${tag}@${DIGEST}"
+          # Look for the main, latest, and sha tags and sign them with cosign
+          echo "DIGEST: $DIGEST"
+          echo "--- end digests ---"
+          echo "TAGS: $TAGS"
+          echo "--- end tags ---"
+          for TAG in $TAGS ; do
+            if [[ $TAG == *"main"* ]] || [[ $TAG == *"latest"* ]] || [[ $TAG == *"sha"* ]]; then
+              cosign sign --yes --verbose "${TAG}@${DIGEST}" || echo "Failed to sign \"${TAG}@${DIGEST}\""
             else
-              echo "Skipping signing of ${tag} tag"
+              echo "Skipping tag ${TAG}"
             fi
           done
 
+          
